on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Filtered
        if: github.event.schedule != '*/5 * * * *'
        run: echo "filtered event"
      - name: Every time
        run: echo "This step will always run"
